version: '3'


services:

  neo4j:
    image: neo4j:4.4.46
    container_name: db_neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: